### ISSUE TITLE
New dataset: canrcm4-wfdei-gem-capa

### ISSUE THREAD

**Issue by julemai** [gwf-uwaterloo/cuizinart#109]
This is a new dataset that is made available by the guys in Saskatoon. It is in NetCDF format but needs some love to fulfill the `CaSPAr` standard (see ToDo). @julemai was in contact already with the contact people in Saskatoon (see contact). **Please don't change the original data but work on a copy.**

**Dataset name:**
canrcm4-wfdei-gem-capa

**Some details:**
- WFDEI-GEM-CaPA used to bias correct CanRCM4
- CaPA is at 40m
- WFDEI has variables in 2m
- spatial resolution: 0.125deg ~ 10km
- temporal resolution: 3hr
- period: 1951-2000
- spatial domain: `lon = [-150,-50] degrees East`, `lat = [31, 72] degrees North`

**Point of contact:**
- Mohamed Elshamy (mohamed.elshamy@usask.ca) for questions on the original data
- Juliane Mai (juliane.mai@uwaterloo.ca) for the NetCDF conversion and `CaSPAr` standard 

**Publication:**
Asong, Z. E., M. Elshamy, D. Princz , H. S. Wheater, J. Pomeroy, A. Pietroniro, and A. Cannon (2019), _High-Resolution Meteorological Forcing Data for Hydrological Modelling and Climate Change Impact Analysis in Mackenzie River Basin_, manuscript submitted to Earth System Science Data (ESSD).

**Meta-data:**
Published on FRDR ([here](https://www.frdr.ca/repo/handle/doi:10.20383/101.0162))

**Data location:**
On Graham (~7 TB)
`/project/6008034/Model_Output/CCRN/CanRCM4/WFDEI-GEM-CaPA/*/*_final.nc4`
where the folder is one of the 15 ensemble member (e.g., `r9i2p1r3`)

**ToDo List:**
The following issues have been already identified and need to be adjusted before the data can be requested through the Cuizinart:
- [ ] files need to have the file extension `nc` rather than `nc4` 
- [ ] dimensions need to be called `rlat` and `rlon` rather than `lat` and `lon`
- [ ] we need one file per year and ensemble member; file naming pattern `YYYY_<ensemble_member_name>.nc`; hence all variables need to be merged to one file
- [ ]  current variable `huss`: needs to be `hus`
```
float hus(time, rlat, rlon)
    hus:long_name = "Specific Humidity at Lowest Model Level (40 m)” ;
    hus:units = "1" ;
```
- [ ]  current variable `pr`: needs to be 
```
float pr(time, rlat, rlon)
    pr:long_name = "Precipitation (surface)” ;
    pr:units = "kg m-2 s-1" ;
```
- [ ] current variable `ps`: needs to be 
```
float ps(time, rlat, rlon)
    ps:long_name = "Surface Pressure (surface)” ;
    ps:units = "Pa" ;
```
- [ ] current variable `rlds(time, rlat, rlon)` can stay as is
- [ ] current variable `rsds(time, rlat, rlon)` can stay as is
- [ ] current variable `sfcWind `: need to be 
```
float sfcWind(time, rlat, rlon)
    sfcWind:long_name = "Zonal (Eastward) Wind (40 m)” ;
    sfcWind:units = "m s**-1" ;
```
- [ ] current variable `tas `: needs to be `ta`
```
float ta(time, rlat, rlon)
    ta:long_name = "Air Temperature (40 m)” ;
    ta:units = "K" ;
```
- [ ] all variables need to be merged to one NetCDF file
- [ ] files have to be cut into files containing only data for one year
- [ ] right now the latitude and longitude variables (not dimensions) `lat` and `lon` are one-dimensional since this is a regular dataset BUT these variables need to be renamed to `rlat` and `rlon` AND two two-dimensional variables `lat(rlat, rlon)` and `lon(rlat, rlon)` have to be added with constant latitude values in `lat` across the `rlon` dimension
 and constant longitude values in `lon` across the `rlat` dimension
- [ ] add a global attribute `gwf_product = "canrcm4-wfdei-gem-capa"`

So far so good. The list might be updated later. This is all I can see right now.

The generation of this dataset required:
- CanRCM4 raw (original Canadian Regional Climate Model projections; 1951-2100)
- WFDEI-GEM-CaPA (product that was used to bias correct CanRCM4 resulting in this product)
- CanRCM4-WFDEI (instead of bias correcting with GEM-CaPA only WFDEI was used)
These datasets might be added later to the Cuizinart...
